# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KeyriAuth0' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KeyriAuth0
  pod 'keyri-pod'

  target 'KeyriAuth0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KeyriAuth0UITests' do
    # Pods for testing
  end

end
